version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
  - package-echosystem: "docker"
    directory: "/example"
    schedule:
      interval: weekly
