[tool.poetry]
name = "checker"
version = "0.0.0"  # DO NOT CHANGE -- set during build
description = "Verify credentials and call out to Duo."
authors = ["Paul Lockaby <paul@paullockaby.com>"]
packages = [{include = "checker", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"
schema = "^0.7.5"
redis = "^4.3.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-mock = "^3.8.2"
pytest-mypy = "^0.9.1"
pytest-flake8 = "^1.1.1"
pytest-cov = "^3.0.0"
pytest-isort = "^3.0.0"
flake8-annotations = "^2.9.0"
flake8-bandit = "^3.0.0"
flake8-broken-line = "^0.5.0"
flake8-builtins = "^1.5.3"
flake8-bugbear = "^22.8.23"
flake8-commas = "^2.1.0"
flake8-comprehensions = "^3.10.0"
flake8-no-implicit-concat = "^0.3.3"
flake8-pylint = "^0.1.3"
flake8-quotes = "^3.3.1"
flake8-simplify = "^0.19.3"
pep8-naming = "^0.13.2"
types-requests = "^2.28.11"
types-redis = "^4.3.19"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
#addopts = "--flake8 --isort --mypy --cov=src --cov-report=term --cov-report=html --log-level=ERROR -p no:warnings"
