[tool.poetry]
name = "apache-external-duo"
version = "0.0.0"  # DO NOT CHANGE -- set during build
description = "Verify credentials and call out to Duo."
authors = ["Paul Lockaby <paul@paullockaby.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
schema = "^0.7.4"
redis = "^4.1.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
pytest-flake8 = "^1.0.7"
flake8-builtins = "^1.5.3"
flake8-bugbear = "^22.1.11"
flake8-comprehensions = "^3.8.0"
flake8-isort = "^4.1.1"
pep8-naming = "^0.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--flake8 -p no:warnings --log-level=ERROR"
