[tool.poetry]
name = "checkduo"
version = "0.0.0"  # DO NOT CHANGE
description = "Verify credentials and call out to Duo."
authors = ["Paul Lockaby <paul@paullockaby.com>"]
packages = [{include = "checkduo", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"
schema = "^0.7.5"
redis = "^4.3.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
pytest-mypy = "^0.10.0"

# mypy dependencies
types-requests = "^2.28.11.2"
types-redis = "^4.3.21.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
